# Generated by Django 2.1 on 2019-12-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default='Doing something awesome one step at a time', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.CharField(default='', max_length=100),
        ),
    ]
