version: '3'

services:
  db:
    image: postgres
  migration:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - db
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment: 
      EMAIL_USER: "${MAIL_USERNAME}"
      EMAIL_PASS: "${MAIL_PASSWORD}"
      DJANGO_AWS_ACCESS_KEY_ID: "${DJANGO_AWS_ACCESS_KEY_ID}"
      DJANGO_AWS_SECRET_ACCESS_KEY: "${DJANGO_AWS_SECRET_ACCESS_KEY}"
      DJANGO_AWS_STORAGE_BUCKET_NAME: "${DJANGO_AWS_STORAGE_BUCKET_NAME}"
    depends_on:
      - migration