# Generated by Django 2.2.8 on 2019-12-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='featured-image.jpg', upload_to='post_featured_images'),
        ),
    ]
