# Generated by Django 2.2.8 on 2019-12-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191218_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='featured-image.png', upload_to='post_featured_images'),
        ),
    ]
