name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: checkit
      run: |
        echo "Build the docker image"
        export BUILD_TAG="$(git tag | sort -V | tail -1)-$(git rev-parse HEAD | cut -c 1-7)"
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git tag | sort -V | tail -1
        TAG=$(git tag | sort -V | tail -1)-$(git rev-parse HEAD | cut -c 1-7)
        docker build -t bvity:v${BUILD_TAG} .
  
  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: iamtito/react-app

    - name: list files
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git tag | sort -V | tail -1
        ls
      
    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag bvify:$(date +%s)
