name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: checkit
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git tag | sort -V | tail -1
        echo GITHUB_REF=${GITHUB_REF}
        echo EXTRACT_GITHUB_REF=${GITHUB_REF##*/}
        echo EXTRACT_GITHUB_REF_HEADS=$(echo ${GITHUB_REF#refs/heads/})
        git describe --tags
        echo "the above is true"
        ls
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag bvify:$(date +%s)
